version: '3.8'

services:
  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/postgres
    networks:
      - webnet
    ports:
      - "8000:80"  # Порт 8000 локально будет проксироваться на 80 порт в контейнере

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - webnet

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    networks:
      - webnet
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - webnet

networks:
  webnet:

volumes:
  db-data:
